export const REGIONS = [
  {
    id: 'pasuruan',
    name: 'PASURUAN',
    slug: 'pasuruan',
    province: 'Jawa Timur',
    color: '#3B82F6',
    gradient: 'from-blue-600 to-blue-800',
    icon: '🏭',
    gasUrl: 'https://script.google.com/macros/s/AKfycbxxsG6GFR8G6_ut7bLbdEZ7oNNc_oYDUxiJz89iQI5pq9YzLVHupFYB1c--Gypwvw/exec',
    excelFile: 'Opname Stockyard Wika Beton PASURUAN.xlsx',
    stockCol: 4,
    titipanCol: 6,
    harSatCol: 33,
    totalRupiahCol: 34,
    rupiahIsString: false,
  },
  {
    id: 'bogor',
    name: 'BOGOR',
    slug: 'bogor',
    province: 'Jawa Barat',
    color: '#10B981',
    gradient: 'from-emerald-600 to-emerald-800',
    icon: '🌿',
    gasUrl: 'https://script.google.com/macros/s/AKfycby9vK3-F0tWTUcqcr8ik9REeudg7Ub6cWAfbfngQ2BwVPzWNAK9Wf-wSF-7f11q-mFl/exec',
    excelFile: 'Opname BOGOR Stockyard Wika Beton.xlsx',
    stockCol: 4,
    titipanCol: 6,
    harSatCol: 23,
    totalRupiahCol: 24,
    rupiahIsString: true, // format "Rp 1,767,911,175"
  },
  {
    id: 'majalengka',
    name: 'MAJALENGKA',
    slug: 'majalengka',
    province: 'Jawa Barat',
    color: '#8B5CF6',
    gradient: 'from-violet-600 to-violet-800',
    icon: '⚙️',
    gasUrl: 'https://script.google.com/macros/s/AKfycbxu89p8G1Wbd_n0TjDb3uFt5m8thqVucXzYsDUIvkjZDBw1EcE-6SkRhUhCafRec1HVJA/exec',
    excelFile: 'Opname Stockyard Wika Beton MAJALENGKA.xlsx',
    stockCol: 4,
    titipanCol: 5,
    harSatCol: 33,
    totalRupiahCol: 34,
    rupiahIsString: false,
  },
  {
    id: 'lampung',
    name: 'LAMPUNG',
    slug: 'lampung',
    province: 'Lampung',
    color: '#F59E0B',
    gradient: 'from-amber-500 to-amber-700',
    icon: '🌾',
    gasUrl: 'https://script.google.com/macros/s/AKfycbzn-5Tyii8XOLCDNZ6hNU-8_RXUAL5oiVFSizkL7gohLpZJx_8tWB-EPuTm8KA3t0BE/exec',
    excelFile: 'Salinan Opname LAMSEL Lampung.xlsx',
    stockCol: 4,
    titipanCol: 5,
    harSatCol: 39,
    totalRupiahCol: 40,
    rupiahIsString: false,
  },
  {
    id: 'subang-karawang',
    name: 'SUBANG KARAWANG',
    slug: 'subang-karawang',
    province: 'Jawa Barat',
    color: '#EF4444',
    gradient: 'from-red-600 to-red-800',
    icon: '🏗️',
    gasUrl: 'https://script.google.com/macros/s/AKfycbzpqKP35jnpZUXftfo1b2GMGud0VkoJ-uiy-VxUidXlotVi1L9-Boo_4GEm1426M4Os/exec',
    excelFile: 'Opname Stockyard Wika Beton Subang Karawang.xlsx',
    stockCol: 4,
    titipanCol: 5,
    harSatCol: 33,
    totalRupiahCol: 34,
    rupiahIsString: false,
  },
  {
    id: 'sumut',
    name: 'SUMUT',
    slug: 'sumut',
    province: 'Sumatera Utara',
    color: '#06B6D4',
    gradient: 'from-cyan-600 to-cyan-800',
    icon: '🌊',
    gasUrl: 'https://script.google.com/macros/s/AKfycbw2gfksN9vdJTt1sRcp4uIjq5M9ia2EzbiwaCBQiH0LuWEmv0SpLS8dJ2sgSJMNv4KQ/exec',
    excelFile: 'Opname Stockyard Wika Beton SUMUT.xlsx',
    stockCol: 4,
    titipanCol: 6,
    harSatCol: 33,
    totalRupiahCol: 34,
    rupiahIsString: false,
  },
  {
    id: 'sulsel',
    name: 'SULSEL',
    slug: 'sulsel',
    province: 'Sulawesi Selatan',
    color: '#EC4899',
    gradient: 'from-pink-600 to-pink-800',
    icon: '⛵',
    gasUrl: 'https://script.google.com/macros/s/AKfycbx73RvAnGR_ZzmcsppfiVQ78CvZ6hzz_t3KkDM5Fa6rtVvlOeACQi6IUnnr5N0PkNR1/exec',
    excelFile: 'DASBOARD SULSEL.xlsx',
    stockCol: 4,
    titipanCol: 5,
    harSatCol: 39,
    totalRupiahCol: 40,
    rupiahIsString: false,
  },
];

export function getRegionBySlug(slug) {
  return REGIONS.find((r) => r.slug === slug) || null;
}
